odin:
    connectionProperties:
        - name: "test"
          url: "rabbitmq://localhost:5672/test-odin?vhost=/test-odin&username=guest&password=guest"
        - name: "test-consumer"
          url: "rabbitmq://localhost:5672/?vhost=/test-odin&username=guest&password=guest"
    rabbitmq:
        - name: "test-odin"
          connectionSource: "test"